### ISSUE TITLE
Details of training time

### ISSUE THREAD

**Issue by BierOne** [orashi/Fast-MoCo#1]
Hi, @orashi. Thanks for your outstanding work! I really appreciate this public code.

Could you please also release the training time for the model and the details of related devices? Thank you.

**Comment by orashi** [comment]
Hi @BierOne , sorry for the late reply.
The information regarding training time and used devices is in Line1-2 of page 7 as in our arxiv v2 paper. Specifically, Fast-MoCo costs 38.5 hours on 16 V100 GPUs for 100 pertaining epochs.
