### ISSUE TITLE
Did you try this on mocov2?

### ISSUE THREAD

**Issue by CoinCheung** [orashi/Fast-MoCo#5]

**Comment by CoinCheung** [comment]
Do you have experiment results of mocov2?

**Comment by orashi** [comment]
Hi Cheung,
We have not done such an experiment before. However, we did try to introduce a negative sample memory queue / non-symmetric loss to our method (early version) before, and they are the major differences between moco2 and v3 in my understanding.  I can recall that the negative queue does not make a significant difference; the non-symmetric loss just makes the result worse even doubling the epochs.

**Comment by CoinCheung** [comment]
Hi orashi,

Thanks for telling me this!! Did you also compared results between mocov2 without symmetric loss and mocov2 with training epoch being doubled?

**Comment by orashi** [comment]
Hi Cheung,
Actually, we didn't have any experiments based on mocov2 before...

**Comment by CoinCheung** [comment]
All right, thanks all the same !!
