### ISSUE TITLE
mc=0.0

### ISSUE THREAD

**Issue by zeallql** [orashi/Fast-MoCo#6]
Hello, is mc=0.0 an internal package? Can you share it?

**Comment by orashi** [comment]
Hi zeallql, thanks for raising this issue! It's an internal package and automatedly detected by pipreqs. But it is not needed for the current code to work, neither will it raise an error if not installed. I've removed it from requirements.txt.

**Comment by zeallql** [comment]
Thank you for your reply, it was very helpful to me
