### ISSUE TITLE
question about adamw optimizer

### ISSUE THREAD

**Issue by CoinCheung** [orashi/Fast-MoCo#7]
Hi,

I noticed in the Appendix that you also tried to pretrain with adamw optimizer. It achieves good results with only 100epoch, what is the training hyper-parameters of adamw(lr, wd, batchsize or so)?

**Comment by orashi** [comment]
Hi CoinCheung, below are the key hyperparams of interest for the reported adamw result, the rest are the same as SGD setup. This setup was for rebuttal purposes so these hyperparams were not well-tuned.

```
optimizer:                  # optimizer details
    type: AdamW
    kwargs:
        betas: [ 0.9, 0.999 ]
        weight_decay: 0.05

lr_scheduler:                   # learning rate scheduler details
    type: WCosConEpoch
    kwargs:
        init_lr: 0.00025
        base_lr: 0.001            # initial leaning rate
        min_lr: 0.0             # mimimal learning rate
        warmup_epoch: 1
        max_epoch: 100 #250300it       # total epochs of training

data: 
    batch_size: 32         # batch size in one GPU, 16 gpus in total, i.e. overall batchsize is 512 (same as SGD setup)
```

**Comment by CoinCheung** [comment]
Thanks for telling me this !!!
